### PR TITLE
Update for Basket Integration

### PR DESCRIPTION
**Pull request by EagleMarcus**
Implemented Add to Basket button functionality.
Updated Db Collection for access to Image addresses and all tables together for Basket integration.

### CODE REVIEW

**Review by rvklenora — COMMENTED** [review]
Hey, just cloned this and tested it out. Ran both the frontend and the backend. Backend fired up perfectly. Frontend told me the following upon opening on browser please resolve or let me know how I can avoid this:

Call Stack
TabLayoutContent
app/(tabs)/_layout.tsx
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js
beginWork
node_modules/react-dom/cjs/react-dom.development.js
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js
recoverFromConcurrentError
node_modules/react-dom/cjs/react-dom.development.js
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js
Collapse all 10 frames
Component Stack
TabLayoutContent
app/(tabs)/_layout.tsx
AuthProvider
app/(tabs)/AuthContext.tsx
Route
node_modules/expo-router/build/Route.js
react_1._default.forwardRef$argument_0
node_modules/expo-router/build/useScreens.js
StaticContainer
node_modules/@react-navigation/core/lib/module/StaticContainer.js
EnsureSingleNavigator
node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js
SceneView
node_modules/@react-navigation/core/lib/module/SceneView.js
React.forwardRef$argument_0
node_modules/react-native-web/dist/exports/View/index.js
React.forwardRef$argument_0
node_modules/react-native-web/dist/exports/View/index.js
React.forwardRef$argument_0
node_modules/react-native-web/dist/exports/View/index.js
Background
node_modules/@react-navigation/elements/lib/module/Background.js
Screen
node_modules/@react-navigation/elements/lib/module/Screen.js
React.forwardRef$argument_0
node_modules/react-native-web/dist/exports/View/index.js
React.forwardRef$argument_0
node_modules/react-native-web/dist/exports/View/index.js
SafeAreaProviderCompat
node_modules/@react-navigation/elements/lib/module/SafeAreaProviderCompat.js
NativeStackView
node_modules/@react-navigation/native-stack/lib/module/views/NativeStackView.js
PreventRemoveProvider
node_modules/@react-navigation/core/lib/module/PreventRemoveProvider.js
NavigationContent
node_modules/@react-navigation/core/lib/module/useComponent.js
React.useRef$argument_0
node_modules/@react-navigation/core/lib/module/useComponent.js
NativeStackNavigator
node_modules/@react-navigation/native-stack/lib/module/navigators/createNativeStackNavigator.js
react_1._default.forwardRef$argument_0
node_modules/expo-router/build/layouts/withLayoutContext.js
ThemeProvider
node_modules/@react-navigation/native/lib/module/theming/ThemeProvider.js
RootLayout
app/_layout.tsx
Route
node_modules/expo-router/build/Route.js
react_1._default.forwardRef$argument_0
node_modules/expo-router/build/useScreens.js
React.forwardRef$argument_0
node_modules/react-native-web/dist/exports/View/index.js
NativeSafeAreaProvider
node_modules/react-native-safe-area-context/lib/module/NativeSafeAreaProvider.web.js
SafeAreaProvider
node_modules/react-native-safe-area-context/lib/module/SafeAreaContext.js
wrapper
node_modules/expo-router/build/ExpoRoot.js
EnsureSingleNavigator
node_modules/@react-navigation/core/lib/module/EnsureSingleNavigator.js
BaseNavigationContainer
node_modules/@react-navigation/core/lib/module/BaseNavigationContainer.js
ThemeProvider
node_modules/@react-navigation/native/lib/module/theming/ThemeProvider.js
NavigationContainerInner
node_modules/expo-router/build/fork/NavigationContainer.js
ContextNavigator
node_modules/expo-router/build/ExpoRoot.js
ExpoRoot
node_modules/expo-router/build/ExpoRoot.js
_HelmetProvider#constructor
node_modules/react-native-helmet-async/lib/index.esm.js
LogBoxStateSubscription
node_modules/@expo/metro-runtime/build/error-overlay/Data/LogBoxData.js
AppContainer
shim:react-native-web/dist/exports/AppRegistry/AppContainer.js

**Comment by EagleMarcus** [comment]
I have removed the conflicted file from my recent commit as it was not necessary for the changes. The rest of the files are ready for your review.

**Review by NathanNguyen-Dev — CHANGES_REQUESTED** [review]
Why is this PR touching layout.tsx and be changing the notification bell function can you give me an explanation. Tks

**Comment by EagleMarcus** [comment]
Thank you for reviewing my pull request. Could you please exclude layout.tsx from the merge? It's not necessary for this commit. I appreciate your help with merging the other changes.

**Comment by EagleMarcus** [comment]
Please note that layout.tsx is not changing anything.

**Comment by EagleMarcus** [comment]
It is currently in its existing state, and I have verified that there are no conflicts detected. It does not cause any issues with the current codebase.

**Review by NathanNguyen-Dev — APPROVED** [review]

**Pull request merged**
